### PR TITLE
Use failover_loadbalancer and failover_amphora for moving LBs between devices

### PR DESCRIPTION
**Pull request by BenjaminLudwigSAP**
Needed for testing driver via telepresence in QA.

### CODE REVIEW

**Review by notandy — COMMENTED** [review]
Hi, I tested it shortly and it seems to do what's expected. Although, I've been thinking (sorry for the change of mood ˆˆ) if it wouldn't make sense to just introduce a new API endpoint, e.g. `loadbalancer_migrate` (e.g. PUT /api/v1/loadbalancers/<UUID>/migrate),  since it seems quite easy implement it?

This way it wouldn't break the API to the provider plugins (although we are not using other plugins)
Just an idea, what do you think?

**Comment by BenjaminLudwigSAP** [comment]
The only advantage I see in making a new endpoint is that the diff would be slightly more pretty.
We would still need semantics for failing over all LBs of a host though (e. g. by allowing either `host` or `load_balancer_id` in the body, but not both).
Breaking the provider API is not really a strong argument since this is already a semi-heavily modified version of Octavia specifically for the F5 provider driver.

I will maybe change this again later to implement `loadbalancer_migrate`, but for now I will merge this and roll out to QA for testing.

**Comment by BenjaminLudwigSAP** [comment]
I'm keeping this branch for now for the aforementioned change to be made later

**Comment by BenjaminLudwigSAP** [comment]
I rolled back the merge (before commit [3d101009](https://github.com/sapcc/octavia/commit/3d101009c272001681f2473e526e4e6a0b73eefe)) in order to make way for other things.

---
When testing again, I couldn't roll out due to breaking tests. Removing or changing them is too much effort, so I will try adding a new endpoint `loadbalancer_migrate` as proposed by @notandy and open a new PR.

**Pull request merged**
